version: "3.9"

services:
  api:
    build: api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
  client:
    build: client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - ./.env
